version: '3.8'

services:
  app:
    build:
      context: .
      args:
        - REACT_APP_BACKEND_URL=${REACT_APP_BACKEND_URL}
    ports:
      - "8080:80"
      - "8001:8001"
    env_file:
      - .env
    depends_on:
      - mongo
    restart: unless-stopped

  mongo:
    image: mongo:6.0
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
      - ./sample_data:/docker-entrypoint-initdb.d
    restart: unless-stopped

volumes:
  mongo_data: