version: '3.8'

services:
  app:
    build:
      context: .
      args:
        - REACT_APP_BACKEND_URL=${REACT_APP_BACKEND_URL}
    ports:
      - "8080:80"
      - "8001:8001"
    env_file:
      - .env.prod
    environment:
      - GOOGLE_PLACES_API_KEY=${GOOGLE_PLACES_API_KEY}
    depends_on:
      - mongo
    restart: unless-stopped
    networks:
      - app-network

  mongo:
    image: mongo:6.0
    # SECURITY FIX: Remove external port exposure to prevent ransomware attacks
    # ports:
    #   - "27017:27017"  # REMOVED - MongoDB should only be accessible internally
    volumes:
      - mongo_data:/data/db
      - ./sample_data:/docker-entrypoint-initdb.d
    restart: unless-stopped
    # Temporarily removed authentication for testing
    # environment:
    #   # Add authentication for additional security
    #   MONGO_INITDB_ROOT_USERNAME: admin
    #   MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongo_data:
