version: '3.8'

services:
  app:
    build:
      context: .
      args:
        - REACT_APP_BACKEND_URL=${REACT_APP_BACKEND_URL}
    ports:
      - "8080:80"
      - "8001:8001"
    env_file: .env.prod
    depends_on:
      - mongo
    restart: always
    volumes:
      - ./docker/nginx-ssl.conf:/etc/nginx/sites-available/default

  mongo:
    image: mongo:6.0
    ports:
      - "27019:27017"
    volumes:
      - mongo_data:/data/db
      - ./sample_data:/docker-entrypoint-initdb.d
    restart: always

volumes:
  mongo_data: