version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:80"
      - "8443:443"
      - "8001:8001"
    environment:
      - MONGO_URL=mongodb://mongo:27017
      - DB_NAME=fire_safety_db
      - OPENROUTER_API_KEY=${OPENROUTER_API_KEY}
      - N8N_WEBHOOK_URL=${N8N_WEBHOOK_URL}
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - ./docker/nginx-ssl.conf:/etc/nginx/sites-available/default
    depends_on:
      - mongo
    restart: unless-stopped

  mongo:
    image: mongo:6.0
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
      - ./sample_data:/docker-entrypoint-initdb.d
    restart: unless-stopped

volumes:
  mongo_data: