version: '3.8'

services:
  app:
    build:
      context: .
      args:
        - REACT_APP_BACKEND_URL=${REACT_APP_BACKEND_URL}
    ports:
      - "8080:80"
      - "8001:8001"
    env_file:
      - .env.prod
    restart: unless-stopped
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
    extra_hosts:
      - "host.docker.internal:host-gateway"
