version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "8001:8001"
    env_file:
      - .env.prod
    restart: unless-stopped
    volumes:
      - ./frontend/build:/app/frontend/build:ro
